### ISSUE TITLE
This is helpful

### ISSUE THREAD

**Issue by AlexFundorin** [shingo45endo/sound-canvas-lcd#3]
I'm currently modelling Sound Canvas in 3D, so this generator was quite helpful. 
I was planning to recreate an LCD in Photoshop, but this is much faster. Thanks.
Can I ask you, what's the purpose of this project?

WIP - https://i.imgur.com/9YOuFd2.png

**Comment by shingo45endo** [comment]
Sorry, I completely overlooked your comment. I have been developing a MIDI file player software by JavaScript. (https://github.com/shingo45endo/remiana; currently, just a logo exists...) This Web Component will be used as a part of this player.
